### PR TITLE
Adding Linux patch

### PR DESCRIPTION
**Pull request by Sqbika**
Linux OS doesn't support uppercase folder names that is addressed by path, because of that, the killfeed showed missing textures. This patch fixes this issue.

### CODE REVIEW

**Comment by Hypnootize** [comment]
I updated all the folders to be lowercase by default that way the patch is not needed, if you could try and let me know if everything works now i would really appreciate it!
and ty for letting me know about it.

**Comment by Sqbika** [comment]
Nope, it doesn't work. The folders need to be lower case too

**Comment by Hypnootize** [comment]
Yeah I made them all lowercase but apparently github wont update them unless I remove and re-add the folder. It should work now I hope.

**Comment by Sqbika** [comment]
Yup, that last patch made it working perfectly! <3

**Pull request closed without merging**
